const { spawn } = require("child_process")
const path = require("path")
const dir = path.join(`${__dirname}/../../client/public/nulis`)
const random = `${dir}/${Math.floor(Math.random() * (1999 - 1111) + 1111)}.jpg`

module.exports.random = random
module.exports.proses = (waktu, hari, nama, kelas, teks) => {
  return spawn("convert", [
    `${dir}/input.jpg`,
    "-font",
    `${dir}/font.ttf`,
    "-size",
    "1024x784",
    "-pointsize",
    "20",
    "-interline-spacing",
    "1",
    "-annotate",
    "+806+78",
    hari,
    "-font",
    `${dir}/font.ttf`,
    "-size",
    "1024x784",
    "-pointsize",
    "18",
    "-interline-spacing",
    "1",
    "-annotate",
    "+806+102",
    waktu,
    "-font",
    `${dir}/font.ttf`,
    "-size",
    "1024x784",
    "-pointsize",
    "18",
    "-interline-spacing",
    "1",
    "-annotate",
    "+360+100",
    nama,
    "-font",
    `${dir}/font.ttf`,
    "-size",
    "1024x784",
    "-pointsize",
    "18",
    "-interline-spacing",
    "1",
    "-annotate",
    "+360+120",
    kelas,
    "-font",
    `${dir}/font.ttf`,
    "-size",
    "1024x784",
    "-pointsize",
    "20",
    "-interline-spacing",
    "-7.5",
    "-annotate",
    "+344+142",
    teks,
    random,
  ])
}
